# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import muebles.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=240, verbose_name='Descripcion del mueble')),
                ('dimensiones', models.TextField(max_length=240, verbose_name='Dimenciones del mueble')),
                ('foto_1', sorl.thumbnail.fields.ImageField(max_length=50, upload_to=muebles.models.change_file_name, verbose_name='1ra foto del mueble')),
                ('foto_2', sorl.thumbnail.fields.ImageField(max_length=50, upload_to=muebles.models.change_file_name, verbose_name='2da foto del mueble')),
                ('foto_3', sorl.thumbnail.fields.ImageField(max_length=50, upload_to=muebles.models.change_file_name, verbose_name='3ra foto del mueble')),
                ('foto_4', sorl.thumbnail.fields.ImageField(max_length=50, upload_to=muebles.models.change_file_name, verbose_name='4ta foto del mueble')),
                ('foto_5', sorl.thumbnail.fields.ImageField(max_length=50, upload_to=muebles.models.change_file_name, verbose_name='5ta foto del mueble')),
                ('modelo', models.CharField(max_length=40, verbose_name='Modelo (Nombre) ')),
                ('oferta', models.SmallIntegerField(default=0, verbose_name='\xbfOferta?')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del mueble')),
                ('slug', models.CharField(blank=True, max_length=140, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria')),
            ],
            bases=(muebles.models.SlugMixin, models.Model),
        ),
    ]
