# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_mueble', models.CharField(choices=[('ninguno', 'Ninguno'), ('comedores', 'Comedores'), ('cocinas', 'Cocinas'), ('closets', 'Closets'), ('banos', 'Banos')], default='ninguno', max_length=10, verbose_name='Categoria del Mueble')),
                ('imagen_categoria', models.ImageField(max_length=50, upload_to='cat_imgs/', verbose_name='Foto de Categoria')),
                ('slug', models.CharField(blank=True, max_length=140, unique=True)),
            ],
        ),
    ]
