# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 04:39
from __future__ import unicode_literals

import categorias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen_categoria',
            field=models.ImageField(max_length=50, upload_to=categorias.models.change_file_name, verbose_name='Foto de Categoria'),
        ),
    ]
